version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=local-user
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=profileMatcher
    ports:
      - '5432:5432'
    volumes:
      -  ./dev/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  campaign-server:
    image: 'mockserver/mockserver:5.15.0'
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /init/requests.json
    volumes:
      - type: bind
        source: ./dev/mockserver
        target: /init

